apiVersion: v1
kind: Secret
metadata:
  name: db-redis-secret
  namespace: statuspage
type: Opaque
stringData:
  DATABASE_URL: msdw-db.cx248m4we6k7.us-east-1.rds.amazonaws.com
  REDIS_URL: redis://master.msdw-cache.7fftml.use1.cache.amazonaws.com:6379/0

